name: Development Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        default: 'linux'
        type: choice
        options:
          - linux
          - windows
          - macos
          - all

jobs:
  build-single:
    name: Build for ${{ github.event.inputs.platform }}
    runs-on: ${{ github.event.inputs.platform == 'windows' && 'windows-latest' || github.event.inputs.platform == 'macos' && 'macos-latest' || 'ubuntu-latest' }}
    if: github.event.inputs.platform != 'all'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies (Linux)
      if: github.event.inputs.platform == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libfreetype6-dev \
          libportmidi-dev \
          python3-dev

    - name: Install Python dependencies
      working-directory: ./projetos/gestao-de-projetos-ageis/jogo
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      working-directory: ./projetos/gestao-de-projetos-ageis/jogo
      run: |
        pyinstaller --onefile \
          --windowed \
          --add-data "imagens:imagens" \
          --name "jogo-plataforma${{ github.event.inputs.platform == 'windows' && '.exe' || '' }}" \
          main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: jogo-plataforma-${{ github.event.inputs.platform }}-dev
        path: ./projetos/gestao-de-projetos-ageis/jogo/dist/
        retention-days: 7

  build-all:
    name: Build for all platforms
    if: github.event.inputs.platform == 'all'
    uses: ./.github/workflows/build-executables.yml